routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$latest_news = DB::table('news')->limit(3)->get();
    return view('welcome', ['latest_news' => $latest_news]);
});
Route::get('/news_detail/{id}', function ($id) {
    $detail = DB::table('news')
    			->where('id', $id)
    			->get();
    $result = $detail->toArray(); 
    $users = DB::table('users')
    			->where('id', $result[0]->user_id)
    			->get();
    $user = $users->toArray();
    return view('news_detail', ['result' => $result, 'user' => $user]);
});

//News Index Admin
Route::resource('news',NewsController::class)->middleware('auth');
Route::resource('users',UsersController::class)->middleware('auth');
Route::get('summernote-image-upload', [NewsController::class, 'show']);
Route::post('post-summernote-image-upload', [NewsController::class, 'store']);
Auth::routes();
Route::get('admin', 'AdminController@index')->name('admin');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('admin') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('news.index') }}">News</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('users.index') }}">Users</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="site_footer">
	<div class="container">
		 <div class="row">
			 <div class="col-sm-8">
				<div class="footer-menu">
					<div class="row">
						<div class="col-sm-4">
							<div class="menu-title">About</div>
							<ul class="footermenu-list">
								<li class="footermenu-item"><a href="" class="menu-link">Home</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">About</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Contact</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Social Media</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Blog</a></li>
							</ul>
						</div>
						<div class="col-sm-4">
							<div class="menu-title">Works</div>
							<ul class="footermenu-list">
								<li class="footermenu-item"><a href="" class="menu-link">Forest Solutions</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Soy Scorecards</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Palm Oil Scorecards</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">School of Fist</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">RSPO</a></li>
							</ul>
						</div>
						<div class="col-sm-4">
							<div class="menu-title">Clients</div>
							<ul class="footermenu-list">
								<li class="footermenu-item"> <a href="" class="menu-link">WWF International</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">RSPO</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Lorem p[sum</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Dolor sit</a></li>
								<li class="footermenu-item"><a href="" class="menu-link">Amet.co</a></li>
							</ul>
						</div>
					</div>
				</div>
			 </div>
			 <div class="col-sm-4">
				 <div class="footer-info">
					 <div class="footerinfo-title">Contact US</div>
					 <p>Ut tristique non elit nec accumsan. Nunc ullamcorper metus at dui luctus, non cursus odio scelerisque. Nulla imperdiet varius arcu quis faucibus. Sed at consectetur lorem.</p>
					 <div class="footer-contact">
						 <form action="" class="contactfooter">
						 <div class="form-group">
						 <textarea class="form-control" id="exampleFormControlTextarea1" rows="2"  placeholder="Message"></textarea>
							 
						</div>
						<div class="form-group group2-input">
							 
							 <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Your email address">
							 <button type="submit" class="btn btn-primary">Submit</button>
						 
							 
						</div> 
						
						 </form>
					 </div>
				 </div>
			 </div>
		 </div>
	</div>
</footer> 

resources/views/layouts/header.blade.php
<header class="site_header">
    <div class="container">
        <div class="top-header">
            <div class="logo-container">
                <a href=""><img src="{{asset("logo_catalyze.png")}}" alt="catalyze"></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#catalyzemenu" aria-controls="catalyzemenu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button> 
            </div>
            <div class="site-menu_container"> 
                <nav class="navbar navbar-expand-lg  ">   
                    <div class="collapse navbar-collapse mainmenu" id="catalyzemenu">
                        <ul class="navbar-nav ">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Works</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Services</a>
                            </li>
                            
                        </ul>
                        <ul class="social-container">
                            <li> <a href="" class="social-item fb"> <img src="{{asset("icon-fb.svg")}}" alt=""></a> </li>
                            <li><a href="" class="social-item tw"> <img src="{{asset("icon-twitter.svg")}}" alt=""></a></li>
                            <li><a href="" class="social-item gplus"> <img src="{{asset("icon-gplus.svg")}}" alt=""></a></li>
                            <li> <button id="search" class="btn-search"><img src="{{asset("icon-search.svg ")}}" alt="" width='20' heigh='20'></button></li>
                        </ul>
                        <!-- <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form> -->
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

resources/views/layouts/layouts_fe.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" content=" ">
        <meta name="description" content=" ">
        <meta name="author" content=" ">
        <title>Catalyze</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">
        <link href="{{ URL::asset('css/app.css') }}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/slick.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/style.css') }}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;700&display=swap" rel="stylesheet">
    </head>
    <body class="page-home static-page">
        <div id="index"></div>
        <script src="{{ asset('js/app.js') }}"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="{{ asset('js/bootstrap.min.js') }}"></script>  
        <script src="{{ asset('js/slick.min.js') }}"></script>  
        <script src="{{ asset('js/main.js') }}"></script> 
    </body>
</html>