routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$latest_news = DB::table('news')->limit(3)->get();
    return view('welcome', ['latest_news' => $latest_news]);
});
Route::get('/news_detail/{id}', function ($id) {
    $detail = DB::table('news')
    			->where('id', $id)
    			->get();
    $result = $detail->toArray(); 
    $users = DB::table('users')
    			->where('id', $result[0]->user_id)
    			->get();
    $user = $users->toArray();
    return view('news_detail', ['result' => $result, 'user' => $user]);
});

//News Index Admin
Route::resource('news',NewsController::class)->middleware('auth');
Route::resource('users',UsersController::class)->middleware('auth');
Route::get('summernote-image-upload', [NewsController::class, 'show']);
Route::post('post-summernote-image-upload', [NewsController::class, 'store']);
Auth::routes();
Route::get('admin', 'AdminController@index')->name('admin');

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = [
        'title', 'detail', 'image'
    ];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;
use Illuminate\Http\Request;
use App\Event;
use Session;
use Auth;
use Illuminate\Support\Facades\DB;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $news = News::latest()->paginate(5);

        return view('admin.news.index',compact('news'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.news.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        if ($request->hasFile('image')) {
            if ($request->file('image')->isValid()) {
                $validated = $request->validate([
                    'title' => 'required',
                    'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                    'detail' => 'required',
                ]);
                $image = $request->file('image');
                $input['imagename'] = time().'.'.$image->getClientOriginalExtension();
                $destinationPath = public_path('/upload');
                $image->move($destinationPath, $input['imagename']);

                $detail = $request->detail;
                $dom = new \DomDocument();
                $dom->loadHtml($detail, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);    
                $images = $dom->getElementsByTagName('img');
                foreach($images as $k => $img){
                    $data = $img->getAttribute('src');
                    list($type, $data) = explode(';', $data);
                    list(, $data)      = explode(',', $data);
                    $data = base64_decode($data);
                    $image_name= "/upload/" . time().$k.'.png';
                    $path = public_path() . $image_name;
                    file_put_contents($path, $data);
                    $img->removeAttribute('src');
                    $img->setAttribute('src', $image_name);
                }
                $detail = $dom->saveHTML();
                $article = new News();
                $email = $request->session()->get('email');
                $collection = DB::table('users')->where('email', $email)->get();
                $result = $collection->toArray();  
                $article->user_id = json_encode($result[0]->id);
                $article->title = $request->get('title');
                $article->detail = $detail;
                $article->image = $input['imagename'];
                $article->save();
                return redirect()->route('news.index')
                ->with('success','News created successfully.');
            } abort(500, 'Could not upload image :(');
        } else {
            $validated = $request->validate([
                'title' => 'required',
                'detail' => 'required',
            ]);
            $detail = $request->detail;
            $dom = new \DomDocument();
            $dom->loadHtml($detail, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);    
            $images = $dom->getElementsByTagName('img');
            foreach($images as $k => $img){
                $data = $img->getAttribute('src');
                list($type, $data) = explode(';', $data);
                list(, $data)      = explode(',', $data);
                $data = base64_decode($data);
                $image_name= "/upload/" . time().$k.'.png';
                $path = public_path() . $image_name;
                file_put_contents($path, $data);
                $img->removeAttribute('src');
                $img->setAttribute('src', $image_name);
            }
            $detail = $dom->saveHTML();
            $article = new News;
            $email = $request->session()->get('email');
            $collection = DB::table('users')->where('email', $email)->get();
            $result = $collection->toArray();       
            $article->user_id = json_encode($result[0]->id);
            $article->title = $request->title;
            $article->detail = $detail;
            $article->save();
            return redirect()->route('news.index')
            ->with('success','News created successfully.');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(News $news)
    {
        return view('admin.news.show',compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(News $news)
    {
        return view('admin.news.edit',compact('news'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, News $news)
    {
        $news->update($request->all());

        return redirect()->route('news.index')
            ->with('success','News updated successfully');
    }


    public function delete_img($image){
        // hapus file
        $gambar = Gambar::where('image',$image)->first();
        File::delete('upload/'.$gambar->file);
     
        // hapus data
        Gambar::where('image',$image)->delete();
     
        return redirect('news.index')->back();
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(News $news)
    {
        $news->delete();

        return redirect()->route('news.index')
            ->with('success','News deleted successfully');
    }
}

resources/views/admin/news/create.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Add News</h3>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('news.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="image">Choose Image</label>
                    <input id="image" type="file" name="image">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="summernote" name="detail"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-success">Add News</button>
            </div>
        </div>

    </form>
@endsection

resources/views/admin/news/edit.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Edit News</h3>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('news.update',$news->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    @if($news->image)
                        <img class="card-img-top" src="{{ asset('upload/'.$news->image) }}" alt="Blog Post Image" style="width: 18rem;">
                    @endif
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" value="{{ $news->title }}" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="summernote" style="height:150px" name="detail">{{ $news->detail }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>

    </form>
@endsection

resources/views/admin/news/index.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>News</h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('news.create') }}">Add News</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="table-responsive">
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Details</th>
                <th width="280px">Actions</th>
            </tr>
            @foreach ($news ?? '' as $nws)
                <tr>
                    <td>{{ $nws->id }}</td>
                    <td>{{ $nws->title }}</td>
                    <td>{{ $nws->detail }}</td>
                    <td>
                        <form action="{{ route('news.destroy',$nws->id) }}" method="POST">

                            <a class="btn btn-info" href="{{ route('news.show',$nws->id) }}">Show</a>

                            <a class="btn btn-primary" href="{{ route('news.edit',$nws->id) }}">Edit</a>

                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>

    {!! $news ?? ''->links() !!}

@endsection

resources/views/admin/news/show.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Show News</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                @if($news->image)
                <img class="card-img-top" src="{{ asset('upload/'.$news->image) }}" alt="Blog Post Image" style="width: 18rem;">
                @endif
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $news->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {!! $news->detail !!}
            </div>
        </div>
    </div>
@endsection